### 예제 1. 문자열에서 유니코드 코드포인트 리스트 만들기 (버전 1)

In [60]:
symbols = "$*&!@"
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


### 예제 2. 문자열에서 유니코드 코드포인트 리스트 만들기 (버전 2)

In [61]:
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


### 예제 3. 지능형 리스트 지역 변수와 주변 변수 구분 예제

In [62]:
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]
print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


### 예제 4. 지능형 리스트로 만든 리스트

In [63]:
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]
print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


### 예제 5. map()/filter()로 만든 리스트

In [64]:
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c > 64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List after map:\n>>> {list(map(ord, symbols))}")

[126] 

Map function:
>>> <map object at 0x110108880>
List after map:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


### 예제 6. 지능형 리스트를 이용한 데카르트 곱

In [65]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirt  = [(color, size) for color in colors for size in sizes]

print(tshirt)

for color in colors:
  for size in sizes:
    print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


### 예제 7. 제너레이터 표현식에서 튜플 초기화하기

In [66]:
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [67]:
import array

ord_s = array.array('I', [ord(symbol) for symbol in symbols])

print(ord_s)

array('I', [33, 35, 94, 38, 38, 35])


### 예제 8. 제너레이터 표현식에서의 데카르트 곱

In [68]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in ('{} {}'.format(c, s) for s in sizes for c in colors):
  print(tshirt)

black S
white S
black M
white M
black L
white L


### 예제 9. 레코드로 사용된 튜플 1

In [69]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'),
                ('BRA', 'CE342567'),
                ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
  print('%s/%s' % passport)
  print('{}/{}'.format(passport[0], passport[1]))
  print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


### 예제 10. 레코드로 사용된 튜플 2

In [70]:
for country, _ in traveler_ids:
  print(country)

USA
BRA
ESP


### 예제 11. 튜플 병렬 할당

In [71]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
print(latitude)
print(longitude)

33.9425
-118.408056


### 예제 12. 튜플 병렬 할당 (swap)

In [72]:
a=10; b=20
b, a = a, b
print(a, b)

20 10


### 예제 13. 튜플 병렬 할당 (함수 인수 전달)

In [73]:
divmod(20, 8)

(2, 4)

In [74]:
t = (20, 8)
divmod(*t)

(2, 4)

In [75]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

### 예제 14. 파일시스템 경로에서 경로명과 파일명 추출

In [76]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

### 예제 15. * 사용으로 병렬 할당 언패킹 1

In [77]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [78]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [79]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

### 예제 16. * 사용으로 병렬 할당 언패킹 2

In [80]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [81]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

### 예제 17. longitude에 접근하기 위해 내포된 튜플 언패킹

In [82]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35, 139)),
    ('Delhi NCR', 'IN', 21, (28, 77)),
    ('Mexico City', 'MX', 20, (19, -99)),
    ('New York-Newark', 'US', 20, (40, -74)),
    ('Sao Paulo', 'BR', 19, (-23, -46))
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (lat, longi) in metro_areas:
  if longi <= 0:
    print(fmt.format(name, lat, longi))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


### 예제 18. 명명된 튜플형을 정의하고 사용하기

In [83]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139,691))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139, 691))

In [84]:
tokyo.population

36.933

In [85]:
tokyo.coordinates

(35.689, 139, 691)

In [86]:
tokyo[1]

'JP'

### 예제 19. 명명된 튜플의 속성과 메서드 ([예제 18]에 이어서)

In [87]:
City._fields

('name', 'country', 'population', 'coordinates')

In [88]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))

In [89]:
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613, long=77.208)}

In [90]:
for key, value in delhi._asdict().items():
  print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


### 예제 20. 슬라이싱 예제

In [91]:
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [92]:
l[2:]

[30, 40, 50, 60]

In [93]:
l[:3]

[10, 20, 30]

In [94]:
l[3:]

[40, 50, 60]

### 예제 21. 단순 텍스트 파일 청구서의 행 항목들

In [95]:
invoice = """
0.....6..................25.........33......40.......
1909  Pimoroni              $17.50     3     $52.50
1489  6mm Tactile           $4.95      2     $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
  print(item[UNIT_PRICE], item[DESCRIPTION])

   $17.5 Pimoroni           
   $4.95 6mm Tactile        
 


### 예제 22. 가변 시퀀스 변형

In [96]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [97]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [98]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [99]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

### 예제 23. 가변 시퀀스 변형 오류 예시

In [100]:
l[2:5] = 100

TypeError: must assign iterable to extended slice

### 예제 24. 올바른 할당문

In [101]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

### 예제 25. 시퀀스에 덧셈 곱셈 수행

In [102]:
l = [1,2,3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [103]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

### 예제 26. 길이가 3인 리스트 3개로 표현한 틱택토 보드

In [104]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [105]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

### 예제 27. 동일한 리스트에 대한 세 개의 참조를 가진 리스트

In [106]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [107]:
weird_board[1][2] = 'O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

### 예제 28. 동일한 리스트에 대한 세 개의 참조를 가진 리스트2

In [108]:
row = ['_'] * 3
board = []
for i in range(3):
  board.append(row)

board[1][2] = 'X'

board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

### 예제 29. [예제26]의 지능형 리스트의 다른 표현

In [109]:
board = []
for i in range(3):
  row = ['_'] * 3
  board.append(row)

print(board)

board[2][0] = 'X'

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

### 예제 30. 가변 시퀀스의 복합 할당 연산자 곱 결과

In [110]:
l = [1,2,3]
id(l)

4599326144

In [111]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [112]:
id(l)

4599326144

### 예제 31. 불변 시퀀스의 복합 할당 연산자 곱 결과

In [113]:
t = (1,2,3)
id(t)

4599383424

In [114]:
t *= 2
id(t)

4599349888

### 예제 32. 퀴즈

In [115]:
t = (1,2, [30,40])
print(t)


t[2] += [50, 60]

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

### 예제 33. 퀴즈 코드 수행 결과

In [116]:
print(t)

(1, 2, [30, 40, 50, 60])


### 예제 34. 리스트 정렬: sorted()

In [117]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [118]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [119]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [120]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

### 예제 35. 리스트 정렬: list.sort()

In [121]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [122]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [123]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

### 예제 36. 커다란 실수 배열의 생성

In [124]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.11531620283979482

### 예제 37. 커다란 실수 배열의 저장/로딩

In [125]:
with open('floats.bin', 'wb') as f:
  floats.tofile(f)

In [126]:
floats2 = array('d')

with open('floats.bin', 'rb') as f:
  floats2.fromfile(f, 10**7)

floats2[-1]

0.11531620283979482

In [127]:
floats2 == floats

True

### 예제 38. 배열 항목 값의 바이트 중 하나 변경

In [128]:
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [129]:
memv[0]

-2

In [130]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [131]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

### 예제 39. numpy.ndarray에서 행과 열을 이용한 기본 연산

In [132]:
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [133]:
type(a)

numpy.ndarray

### 예제 40. numpy.ndarray에서 행과 열을 이용한 기본 연산 2

In [134]:
a.shape

(12,)

In [135]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 예제 41. numpy.ndarray에서 행과 열을 이용한 기본 연산 3

In [136]:
a[2]

array([ 8,  9, 10, 11])

In [137]:
a[2,1]

np.int64(9)

In [138]:
a[:, 1]

array([1, 5, 9])

### 예제 42. numpy.ndarray에서 행과 열을 이용한 기본 연산 4

In [139]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### 예제 43. 덱 이용하기 1

In [140]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [141]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [142]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

### 예제 44. 덱 이용하기 2

In [143]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [144]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)

In [145]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)